services:
  db:
    build: .
    ports:
      - ${PORT:-5432}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PASSWORD:-duckdb}
    volumes:
      - pg_duckpipe_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_duckpipe_data:
